apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: innowise
data:
  USER_SERVICE_URL: "http://user-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8083"
  AUTHENTICATION_SERVICE_URL: "http://authentication-service:8082"
  PAYMENT_SERVICE_URL: "http://payment-service:8086"

  KEYCLOAK_ISSUER_URI: "http://keycloak.local:8081/realms/user-service"
  KEYCLOAK_URL: "http://keycloak.local:8081"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_USERNAME: "default"

  PAYMENT_MONGODB_URI: "mongodb://payment-service-mongodb:27017/paymentservice"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  API_GATEWAY_URL: "http://api-gateway:8085"