apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-postgres-init
  namespace: innowise
data:
  init.sql: |
    CREATE SCHEMA IF NOT EXISTS orderservice;

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-service-postgres-pvc
  namespace: innowise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-postgres
  namespace: innowise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-postgres

  template:
    metadata:
      labels:
        app: order-service-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: ORDER_DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: ORDER_DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: ORDER_DB_PASSWORD

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - postgres
            initialDelaySeconds: 15
            periodSeconds: 10

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: order-service-postgres-pvc

        - name: init-script
          configMap:
            name: order-service-postgres-init

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-postgres
  namespace: innowise
spec:
  selector:
    app: order-service-postgres
  ports:
    - port: 5432
      targetPort: 5432