apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: innowise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service

    spec:
      hostAliases:
        - ip: "192.168.65.254"
          hostnames:
            - "keycloak.local"

      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8086

          env:
            - name: SERVER_PORT
              value: "8086"

            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: MONGODB_URI

          envFrom:
            - configMapRef:
                name: application-config

            - secretRef:
                name: application-secrets

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10